<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);
$law=['services.php'=>["homepage_source_value( 'law-01', 'services' )"],'about.php'=>["homepage_source_value( 'law-01', 'about' )"],'team.php'=>["homepage_source_value( 'law-01', 'team' )"],'topics.php'=>["homepage_source_value( 'law-01', 'knowledge' )"],'latest.php'=>["homepage_source_value( 'law-01', 'knowledge' )"],'analysis.php'=>["homepage_source_value( 'law-01', 'case_analysis' )"],'news.php'=>["homepage_source_value( 'law-01', 'legal_news' )"],'process.php'=>["homepage_source_value( 'law-01', 'process' )"],'faq.php'=>["homepage_source_value( 'law-01', 'faq' )"],'final-cta.php'=>["homepage_source_value( 'law-01', 'contact' )"],'profile.php'=>["homepage_source_value( 'law-01', 'about' )","homepage_source_value( 'law-01', 'team' )","homepage_source_value( 'law-01', 'services' )","homepage_source_value( 'law-01', 'process' )","homepage_source_value( 'law-01', 'faq' )"],'hero.php'=>["homepage_source_value( 'law-01', 'hero' )","homepage_source_value( 'law-01', 'hero_variant' )","homepage_source_value( 'law-01', 'hero_page' )","homepage_source_value( 'law-01', 'contact' )","homepage_source_value( 'law-01', 'services' )"]];
foreach($law as $file=>$required){$source=(string)file_get_contents($root.'/template-parts/homepage/law-01/'.$file);foreach($required as $needle)assert(str_contains($source,$needle),"Law {$file} missing {$needle}");foreach(["setting( 'homepage_services_page'","setting( 'homepage_about_page'","setting( 'homepage_team_page'","setting( 'homepage_knowledge_terms'","setting( 'homepage_case_analysis_term'","setting( 'homepage_legal_news_term'","setting( 'homepage_process_page'","setting( 'homepage_faq_page'","setting( 'homepage_contact_page'","setting( 'homepage_hero_block'","setting( 'homepage_hero_page'","setting( 'homepage_hero_variant'"] as $forbidden)assert(!str_contains($source,$forbidden),"Law {$file} generic read {$forbidden}");}
$curtain=['hero.php'=>["homepage_source_value( 'curtain-01', 'hero' )","homepage_source_value( 'curtain-01', 'contact' )"],'proof-strip.php'=>["homepage_source_value( 'curtain-01', 'proof' )"],'about.php'=>["homepage_source_value( 'curtain-01', 'about' )","homepage_source_value( 'curtain-01', 'about_image' )"],'knowledge.php'=>["homepage_source_value( 'curtain-01', 'knowledge' )"],'process.php'=>["homepage_source_value( 'curtain-01', 'process' )"],'projects.php'=>["homepage_source_value( 'curtain-01', 'projects' )"],'final-cta.php'=>["homepage_source_value( 'curtain-01', 'contact' )"]];
foreach($curtain as $file=>$required){$source=(string)file_get_contents($root.'/template-parts/homepage/curtain-01/'.$file);foreach($required as $needle)assert(str_contains($source,$needle),"Curtain {$file} missing {$needle}");}
$discovery=(string)file_get_contents($root.'/inc/theme/provisioning-discovery.php');$runner=(string)file_get_contents($root.'/inc/theme/provisioning-runner.php');$readiness=(string)file_get_contents($root.'/inc/theme/provisioning-readiness.php');
assert(str_contains($discovery,"homepage_source_value( 'law-01'"));assert(str_contains($readiness,"homepage_source_value( 'law-01'"));
foreach(['homepage_law01_hero_page','homepage_law01_services_page','homepage_law01_about_page','homepage_law01_team_page','homepage_law01_process_page','homepage_law01_faq_page','homepage_law01_contact_page','homepage_law01_knowledge_terms','homepage_law01_case_analysis_term','homepage_law01_legal_news_term'] as $key)assert(str_contains($runner,$key),"Runner missing {$key}");
foreach(["\$s['homepage_services_page'] =","\$s['homepage_about_page'] =","\$s['homepage_team_page'] =","\$s['homepage_process_page'] =","\$s['homepage_faq_page'] =","\$s['homepage_contact_page'] =","\$s['homepage_knowledge_terms'] =","\$s['homepage_case_analysis_term'] =","\$s['homepage_legal_news_term'] ="] as $forbidden)assert(!str_contains($runner,$forbidden),"Runner legacy write {$forbidden}");
echo "PASS: D-038 Homepage consumers resolve sources by preset\n";
