<?php
declare(strict_types=1);
if(!defined('ABSPATH')) define('ABSPATH',__DIR__.'/');
class WP_Error{public string $message;function __construct($c='e',$m='error'){$this->message=$m;}function get_error_message(){return $this->message;}}
function is_wp_error($v){return $v instanceof WP_Error;}
class WP_Post{public int $ID;public string $post_type='page';public string $post_status='publish';public string $post_title='';public string $post_content='';public int $post_parent=0;function __construct($id,$title='',$content='',$status='publish'){$this->ID=$id;$this->post_title=$title;$this->post_content=$content;$this->post_status=$status;}}
class WP_Term{public int $term_id;public string $name;public string $taxonomy;function __construct($id,$n='',$tax='category'){$this->term_id=$id;$this->name=$n;$this->taxonomy=$tax;}}
$GLOBALS['fi_posts']=[77=>new WP_Post(77,'Giới thiệu','Pre-existing same-title page')];$GLOBALS['fi_terms']=[];$GLOBALS['fi_menus']=[];$GLOBALS['fi_next_post']=100;$GLOBALS['fi_next_menu']=300;$GLOBALS['fi_post_meta']=[];$GLOBALS['fi_term_meta']=[];$GLOBALS['fi_options']=['show_on_front'=>'posts','page_on_front'=>0];$GLOBALS['fi_mods']=['aznet_theme_settings'=>['schema_version'=>2,'homepage_preset'=>'off'],'nav_menu_locations'=>[]];
function get_post($id){return $GLOBALS['fi_posts'][$id]??null;}function get_pages($a=[]){return array_values($GLOBALS['fi_posts']);}function get_categories($a=[]){return array_values($GLOBALS['fi_terms']);}function wp_count_posts($t='post'){return(object)['publish'=>0,'draft'=>0,'private'=>0,'pending'=>0,'future'=>0];}
function get_option($k,$d=false){return $GLOBALS['fi_options'][$k]??$d;}function update_option($k,$v){$GLOBALS['fi_options'][$k]=$v;return true;}function get_theme_mod($k,$d=false){return $GLOBALS['fi_mods'][$k]??$d;}function set_theme_mod($k,$v){$GLOBALS['fi_mods'][$k]=$v;}function get_nav_menu_locations(){return $GLOBALS['fi_mods']['nav_menu_locations']??[];}
function wp_insert_post($data,$err=false){$id=$GLOBALS['fi_next_post']++;$p=new WP_Post($id,$data['post_title']??'',$data['post_content']??'',$data['post_status']??'publish');$p->post_parent=(int)($data['post_parent']??0);$GLOBALS['fi_posts'][$id]=$p;return$id;}function wp_update_post($d){$id=(int)$d['ID'];if(isset($d['post_content']))$GLOBALS['fi_posts'][$id]->post_content=(string)$d['post_content'];return$id;}function wp_delete_post($id,$force=false){unset($GLOBALS['fi_posts'][$id]);return true;}
function update_post_meta($id,$k,$v){$GLOBALS['fi_post_meta'][$id][$k]=$v;return true;}function get_post_meta($id,$k,$single=true){return$GLOBALS['fi_post_meta'][$id][$k]??'';}function get_posts($a=[]){$out=[];foreach($GLOBALS['fi_posts'] as $p){$ok=true;foreach(($a['meta_query']??[])as$q){if(($GLOBALS['fi_post_meta'][$p->ID][$q['key']]??null)!==($q['value']??null))$ok=false;}if($ok)$out[]=$p;}return$out;}
function wp_insert_term($n,$tax,$a=[]){$id=count($GLOBALS['fi_terms'])+200;$GLOBALS['fi_terms'][$id]=new WP_Term($id,$n,$tax);return['term_id'=>$id,'term_taxonomy_id'=>$id];}function wp_delete_term($id,$tax){unset($GLOBALS['fi_terms'][$id]);return true;}function update_term_meta($id,$k,$v){$GLOBALS['fi_term_meta'][$id][$k]=$v;return true;}function get_term_meta($id,$k,$single=true){return$GLOBALS['fi_term_meta'][$id][$k]??'';}function get_term($id,$tax=''){return$GLOBALS['fi_terms'][$id]??null;}
function get_terms($a=[]){$tax=$a['taxonomy']??'category';$pool=$tax==='nav_menu'?$GLOBALS['fi_menus']:$GLOBALS['fi_terms'];$out=[];foreach($pool as $term){$ok=true;foreach(($a['meta_query']??[])as$q){if(($GLOBALS['fi_term_meta'][$term->term_id][$q['key']]??null)!==($q['value']??null))$ok=false;}if($ok)$out[]=$term;}return$out;}
function wp_create_nav_menu($name){$id=$GLOBALS['fi_next_menu']++;$GLOBALS['fi_menus'][$id]=new WP_Term($id,$name,'nav_menu');return$id;}function wp_delete_nav_menu($id){unset($GLOBALS['fi_menus'][$id]);return true;}function wp_get_nav_menu_items($id){return[];}function wp_update_nav_menu_item($m,$i,$a){return 1;}
$root=dirname(__DIR__,2);foreach(['settings.php','provisioning-blueprints.php','provisioning-discovery.php','provisioning-plan.php','provisioning-provenance.php','provisioning-runner.php']as$f)require_once$root.'/inc/theme/'.$f;
$sel=['pages'=>['home'=>['action'=>'create','object_id'=>0],'about'=>['action'=>'create','object_id'=>0],'services'=>['action'=>'create','object_id'=>0],'contact'=>['action'=>'create','object_id'=>0]],'categories'=>[],'menu'=>['action'=>'create','menu_id'=>0],'front_page'=>['action'=>'set_to_role','role'=>'home']];
$p1=\AZnet\Theme\provisioning_build_plan('law01-v1',$sel,\AZnet\Theme\provisioning_discovery());$r1=\AZnet\Theme\provisioning_apply_plan($p1);assert($r1['ok']===true,implode(';',$r1['errors']));$about=(int)$r1['page_ids']['about'];assert($about!==77,'Unmarked same-title Page must not be auto-reused');
wp_update_post(['ID'=>$about,'post_content'=>'User-authored content']);
$GLOBALS['fi_posts'][88]=new WP_Post(88,'Real About','Real mapped content');$s=\AZnet\Theme\settings();$s['homepage_about_page']=88;set_theme_mod('aznet_theme_settings',\AZnet\Theme\normalize_settings($s));
$p2=\AZnet\Theme\provisioning_build_plan('law01-v1',$sel,\AZnet\Theme\provisioning_discovery());$r2=\AZnet\Theme\provisioning_apply_plan($p2);assert($r2['ok']===true,implode(';',$r2['errors']));assert(count($r2['created'])===0,'Rerun must create zero provisioning roles');assert(get_post($about)->post_content==='User-authored content','Rerun must preserve user edits');assert(\AZnet\Theme\settings()['homepage_about_page']===88,'Explicit current Content Map must win over old provenance');assert(count($GLOBALS['fi_menus'])===1,'Rerun must not duplicate provisioning menu');
echo "PASS: Provisioning idempotency/current-mapping/user-edit contract\n";
