<?php
/**
 * Title: Page Kit — Team & Expertise
 * Slug: aznet-theme/page-team-expertise
 * Categories: aznet-theme-pages
 * Description: Portable team and expertise Page structure with explicit verified-profile placeholders.
 */
?>
<!-- wp:group {"align":"wide","className":"aznet-theme-pattern aznet-theme-page-kit aznet-theme-page-kit--team","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide aznet-theme-pattern aznet-theme-page-kit aznet-theme-page-kit--team">
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__intro","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__intro"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Đội ngũ và chuyên môn', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng mô tả đội ngũ, vai trò và phạm vi chuyên môn đã được xác minh.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:columns {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__profiles"} --><div class="wp-block-columns aznet-theme-page-kit__section aznet-theme-page-kit__profiles"><!-- wp:column --><div class="wp-block-column aznet-theme-page-kit__card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Thay bằng hồ sơ thực tế', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng tên, vai trò, kinh nghiệm và bằng chứng chuyên môn đúng với hồ sơ thật.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column aznet-theme-page-kit__card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Thay bằng hồ sơ thực tế', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng thông tin hồ sơ thực tế đã được người phụ trách xác nhận.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column aznet-theme-page-kit__card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Thay bằng hồ sơ thực tế', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng vai trò, phạm vi trách nhiệm và thông tin chuyên môn có thể kiểm chứng.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__trust","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__trust"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Năng lực và bằng chứng', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:columns --><div class="wp-block-columns"><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Chuyên môn', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng lĩnh vực chuyên môn thực tế và phạm vi thực hành phù hợp.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Bằng chứng', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng nguồn xác minh, tài liệu hoặc thành quả có thể công khai.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__cta","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__cta"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Kết nối đúng người phụ trách', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng CTA dẫn tới kênh liên hệ hoặc hồ sơ thực tế phù hợp.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#"><?php esc_html_e( 'Thay bằng CTA đội ngũ thực tế', 'aznet-theme' ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->
</div><!-- /wp:group -->
