<?php
/**
 * Title: Page Kit — Content Landing
 * Slug: aznet-theme/page-content-landing
 * Categories: aznet-theme-pages
 * Description: Portable content landing Page structure with authority, native query, FAQ and CTA sections.
 */
?>
<!-- wp:group {"align":"wide","className":"aznet-theme-pattern aznet-theme-page-kit aznet-theme-page-kit--content-landing","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide aznet-theme-pattern aznet-theme-page-kit aznet-theme-page-kit--content-landing">
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__intro","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__intro"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Trung tâm nội dung', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng mô tả phạm vi nội dung, đối tượng đọc và nguyên tắc biên tập thực tế.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:quote {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__authority"} --><blockquote class="wp-block-quote aznet-theme-page-kit__section aznet-theme-page-kit__authority"><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng trích dẫn, tuyên bố chuyên môn hoặc nguyên tắc đã được xác minh và có chủ thể chịu trách nhiệm.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></blockquote><!-- /wp:quote -->
<!-- wp:group {"className":"aznet-theme-page-kit__section","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Nội dung mới', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng lời dẫn phù hợp với chuyên mục và chiến lược nội dung thực tế.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --><!-- wp:query {"queryId":0,"query":{"perPage":6,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false},"displayLayout":{"type":"list"}} --><div class="wp-block-query"><!-- wp:post-template {"layout":{"type":"grid","columnCount":3}} --><!-- wp:group {"className":"aznet-theme-page-kit__card","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__card"><!-- wp:post-title {"isLink":true,"fontSize":"lg"} /--><!-- wp:post-excerpt {"moreText":""} /--></div><!-- /wp:group --><!-- /wp:post-template --><!-- wp:query-no-results --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng hướng dẫn khi chưa có nội dung xuất bản phù hợp.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --><!-- /wp:query-no-results --></div><!-- /wp:query --></div><!-- /wp:group -->
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__faq","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__faq"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Câu hỏi định hướng', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:details --><details class="wp-block-details"><summary><?php esc_html_e( 'Thay bằng câu hỏi thực tế người đọc thường cần làm rõ', 'aznet-theme' ); ?></summary><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng câu trả lời chính xác, có nguồn và giới hạn phù hợp.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></details><!-- /wp:details --></div><!-- /wp:group -->
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__cta","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__cta"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Tiếp tục hành trình', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng CTA phù hợp với mục tiêu thật của hệ thống nội dung.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#"><?php esc_html_e( 'Thay bằng CTA nội dung thực tế', 'aznet-theme' ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->
</div><!-- /wp:group -->
