<?php
/**
 * Title: Page Kit — Services
 * Slug: aznet-theme/page-services
 * Categories: aznet-theme-pages
 * Description: Portable Services Page structure with service, process, FAQ and CTA placeholders.
 */
?>
<!-- wp:group {"align":"wide","className":"aznet-theme-pattern aznet-theme-page-kit aznet-theme-page-kit--services","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide aznet-theme-pattern aznet-theme-page-kit aznet-theme-page-kit--services">
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__intro","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__intro"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Dịch vụ và giá trị cung cấp', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng mô tả phạm vi dịch vụ thực tế đã được khách hàng xác minh.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:columns {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__grid"} --><div class="wp-block-columns aznet-theme-page-kit__section aznet-theme-page-kit__grid"><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Dịch vụ mẫu', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng tên, đối tượng phù hợp và kết quả có thể cung cấp của dịch vụ thật.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Dịch vụ mẫu', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng mô tả dịch vụ thật, tránh hứa hẹn kết quả chưa được chứng minh.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Dịch vụ mẫu', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng phạm vi, điều kiện và thông tin cần biết của dịch vụ thực tế.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:group {"className":"aznet-theme-page-kit__section","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Quy trình làm việc', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:columns --><div class="wp-block-columns"><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Bước mẫu', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng bước thực tế trong quy trình phục vụ.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Bước mẫu', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng trách nhiệm và đầu ra thực tế của bước này.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Bước mẫu', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng cách bàn giao hoặc hỗ trợ thực tế sau dịch vụ.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__faq","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__faq"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Câu hỏi thường gặp', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:details --><details class="wp-block-details"><summary><?php esc_html_e( 'Thay bằng câu hỏi thực tế của khách hàng', 'aznet-theme' ); ?></summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} --><p><?php esc_html_e( 'Thay bằng câu trả lời chính xác, có điều kiện và phạm vi rõ ràng.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></details><!-- /wp:details --><!-- wp:details --><details class="wp-block-details"><summary><?php esc_html_e( 'Thay bằng câu hỏi thực tế của khách hàng', 'aznet-theme' ); ?></summary><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng câu trả lời đã được khách hàng xác minh.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></details><!-- /wp:details --></div><!-- /wp:group -->
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__cta","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__cta"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Trao đổi nhu cầu thực tế', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng CTA phù hợp với cách khách hàng tiếp nhận yêu cầu dịch vụ.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#"><?php esc_html_e( 'Thay bằng CTA dịch vụ thực tế', 'aznet-theme' ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->
</div><!-- /wp:group -->
