<?php
/**
 * Title: Page Kit — Contact
 * Slug: aznet-theme/page-contact
 * Categories: aznet-theme-pages
 * Description: Portable contact Page structure using verified contact placeholders and no form engine.
 */
?>
<!-- wp:group {"align":"wide","className":"aznet-theme-pattern aznet-theme-page-kit aznet-theme-page-kit--contact","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide aznet-theme-pattern aznet-theme-page-kit aznet-theme-page-kit--contact">
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__intro","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__intro"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Liên hệ', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng hướng dẫn liên hệ phù hợp với cách tiếp nhận thực tế của khách hàng.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:columns {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__contact-grid"} --><div class="wp-block-columns aznet-theme-page-kit__section aznet-theme-page-kit__contact-grid"><!-- wp:column --><div class="wp-block-column aznet-theme-page-kit__card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Thông tin liên hệ', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng địa chỉ, điện thoại hoặc thông tin liên hệ đã được xác minh.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column aznet-theme-page-kit__card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Kênh tiếp nhận', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng kênh tiếp nhận yêu cầu thực tế và hướng dẫn sử dụng kênh đó.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column aznet-theme-page-kit__card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Thời gian phản hồi', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng khung thời gian hoặc kỳ vọng phản hồi đã được khách hàng xác nhận.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__cta","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__cta"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Chọn kênh phù hợp', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng CTA dẫn tới kênh liên hệ thực tế; không thêm biểu mẫu khi chưa có owner cho form workflow.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#"><?php esc_html_e( 'Thay bằng CTA liên hệ thực tế', 'aznet-theme' ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->
</div><!-- /wp:group -->
