<?php
/**
 * Title: Page Kit — About
 * Slug: aznet-theme/page-about
 * Categories: aznet-theme-pages
 * Description: Portable About Page structure using verified-content placeholders only.
 */
?>
<!-- wp:group {"align":"wide","className":"aznet-theme-pattern aznet-theme-page-kit aznet-theme-page-kit--about","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide aznet-theme-pattern aznet-theme-page-kit aznet-theme-page-kit--about">
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__intro","layout":{"type":"constrained"}} -->
<div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__intro"><!-- wp:paragraph {"className":"aznet-theme-pattern__eyebrow"} --><p class="aznet-theme-pattern__eyebrow"><?php esc_html_e( 'Giới thiệu', 'aznet-theme' ); ?></p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Một phần mở đầu rõ về tổ chức và giá trị mang lại', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng nội dung giới thiệu đã được khách hàng xác minh.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:columns {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__alternating"} --><div class="wp-block-columns aznet-theme-page-kit__section aznet-theme-page-kit__alternating"><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Câu chuyện hình thành', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng câu chuyện thực tế, có nguồn và mốc thông tin đã xác minh.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Cách làm việc', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng nguyên tắc làm việc và cam kết có thể kiểm chứng của khách hàng.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:columns {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__alternating"} --><div class="wp-block-columns aznet-theme-page-kit__section aznet-theme-page-kit__alternating"><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Năng lực cốt lõi', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng năng lực thực tế và phạm vi chuyên môn đã được xác minh.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Điều khách hàng có thể kỳ vọng', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng kết quả, tiêu chuẩn phục vụ hoặc bằng chứng phù hợp với hồ sơ thực tế.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:columns {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__trust"} --><div class="wp-block-columns aznet-theme-page-kit__section aznet-theme-page-kit__trust"><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Điểm tin cậy', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng bằng chứng tin cậy đã được xác minh.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Điểm khác biệt', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng khác biệt có căn cứ, tránh dùng tuyên bố quảng cáo không kiểm chứng.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php esc_html_e( 'Bằng chứng hỗ trợ', 'aznet-theme' ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng tài liệu, dự án hoặc nguồn tham chiếu thực tế khi có.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:group {"className":"aznet-theme-page-kit__section aznet-theme-page-kit__cta","layout":{"type":"constrained"}} --><div class="wp-block-group aznet-theme-page-kit__section aznet-theme-page-kit__cta"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading"><?php esc_html_e( 'Bước tiếp theo', 'aznet-theme' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php esc_html_e( 'Thay bằng lời kêu gọi hành động phù hợp với mục tiêu thật của trang.', 'aznet-theme' ); ?></p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#"><?php esc_html_e( 'Thay bằng CTA thực tế', 'aznet-theme' ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->
</div><!-- /wp:group -->
